zookeeper_version("3.4.4")
zookeeper_root_dir("/var/lib/zookeeper")
zookeeper_config_dir("/var/lib/zookeeper/conf")
zookeeper_data_dir("/var/lib/zookeeper/data")
zookeeper_client_port("2181")
zookeeper_myid(nil)
zookeeper_server_list(nil)
